### ISSUE TITLE
How can I stop to receive messages?

### ISSUE THREAD

**Issue by JeanExtreme002** [ViLsonCake/avgeek-telegram-bot#1]
Hi @ViLsonCake !

This is a really nice project, I really liked it! I tried using your bot and it works very nice. But I would like to stop receiving messages from it now and there is no command to stop it yet.

**Comment by ViLsonCake** [comment]
Thanks @JeanExtreme002 for the feedback!

I'll now look into solving this issue.

**Comment by ViLsonCake** [comment]
I've added functionality to disable notifications using the **/changemode** command, more details can be found in the [new release](https://github.com/ViLsonCake/avgeek-telegram-bot/releases/tag/v4.1).

Thanks again @JeanExtreme002.
